# Generated by Django 3.1.2 on 2020-10-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201031_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripcion',
            new_name='description',
        ),
    ]
