# Generated by Django 3.1.3 on 2020-11-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='subscribed',
            field=models.BooleanField(null=True),
        ),
    ]
