# Generated by Django 3.1.3 on 2020-11-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20201115_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingpreference',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
